### PR TITLE
Matrix order in definition of Euler Angles #495

### PR DESCRIPTION
**Pull request by joullsson**
This is taken from https://github.com/OpenSimulationInterface/open-simulation-interface/issues/495

Describe the bug
In https://opensimulationinterface.github.io/osi-documentation/open-simulation-interface/structosi3_1_1Orientation3d.html there are two different issues

while the text correctly interprets the ISO8855 as describing the intrinsic rotation z-y'-x'', the formula that defines the rotation as a product of three elementary rotations is in reverse order.
the preferred angular range is given as [-pi,pi]. However, euler angles are not unique on the cube [-pi, pi]^3.
Describe the expected behavior
The expected behavior can simply be taken from wikipedia https://de.wikipedia.org/wiki/Eulersche_Winkel#Roll-,_Nick-_und_Gierwinkel:_z-y%E2%80%B2-x%E2%80%B3-Konvention. This means that

the formula should read R_{yaw,pitch,roll} = R_{yaw} * R_{pitch} * R_{roll}
the angular range should be set to [-pi, pi] x [-pi/2, pi/2] x [-pi , pi] in order to make it unique (in the interior at least)
@joullsson

### CODE REVIEW

**Comment by jola6897** [comment]
Hi, as mentioned in my comment in #495, the rotation order should be correct, but you are right that the value ranges need to be specified.

**Comment by kmeids** [comment]
@joullsson,

Is it possible for you to attend our next CCB meeting and explain your changes in order to see whether we can merge this pull request?
If yes could you please contact Stefan Cyliax (stefan.cyliax@asam.net) for more info?

Thanks!

**Comment by stefancyliax** [comment]
OSI CCB:
- another topic for the architecture meeting. We have to decide if this can be put into 3.4. Author is not available this month.

**Comment by kmeids** [comment]
**CCB Output 21.07.2021**
1. Changes address the issues.
2. Wait till @joullsson comes back from vacation to do the DCO, @stefancyliax will contact him.
3. @stefancyliax to merge the pull request after the DCO is fixed.

**Comment by joullsson** [comment]
Thanks for reviewing, hopefully the DCO is fixed now!

**Review by stefancyliax — APPROVED** [review]
This was reviewed in the CCB on 21.07.2021.

**Pull request merged**
