### PR TITLE
Correct typos in model_reference comments in osi_groundtruth.proto

### PR DESCRIPTION
**Pull request by hschoen**
PS: maybe the expression "opaque reference" could be elaborated.

﻿#### Reference to a related issue in the repository
Add a reference to a related issue in the repository.

#### Add a description
Add a description of the changes proposed in the pull request.

**Some questions to ask**:
What is this change?
What does it fix?
Is this a bug fix or a feature? Does it break any existing functionality or force me to update to a new version?
How has it been tested?

#### Take this checklist as orientation for yourself, if this PR is ready for the Change Control Board:
- [ ] My suggestion follows the [style and contributors guidelines](https://opensimulationinterface.github.io/osi-documentation/open-simulation-interface/doc/howtocontribute.html).
- [ ] I have taken care about the [documentation](https://opensimulationinterface.github.io/osi-documentation/open-simulation-interface/doc/commenting.html).
- [ ] I have done the [DCO signoff](https://opensimulationinterface.github.io/osi-documentation/open-simulation-interface/doc/howtocontribute.html#developer-certification-of-origin-dco).
- [ ] My changes generate no errors when passing CI tests. 
- [ ] I have successfully implemented and tested my fix/feature locally.
- [ ] Appropriate reviewer(s) are assigned.

If you can’t check all of them, please explain why.
If all boxes are checked or commented and you have achieved at least one positive review, you can assign the label ReadyForCCBReview!

### CODE REVIEW

**Review by pmai — APPROVED** [review]
Seem obvious fixes that should be included ASAP.

**Comment by hschoen** [comment]
Hallo Pierre,

da hast du ja beeindruckend schnell reagiert. 👍
Ich weiß nicht, ob mein Kommentar „PS: maybe the expression "opaque reference" could be elaborated.“ im PR hier an der rechten Stelle war, aber das könnte man evtl. noch ausformulieren.

Mit freundlichen Grüßen / Best regards

Dr. Helmut Schoen

HF-Sensoren, EMV (CR/AEL1)
Robert Bosch GmbH | Postfach 10 60 50 | 70049 Stuttgart | GERMANY | www.bosch.com
Tel. +49 711 811-10880 | Mobil +49 173 9187997 | Telefax +49 711 811 | Threema<threema://add/?id=K286UVMU> / Threema Work<threemawork://add/?id=K286UVMU>: K286UVMU | Helmut.Schoen@de.bosch.com<mailto:Helmut.Schoen@de.bosch.com>

Sitz: Stuttgart, Registergericht: Amtsgericht Stuttgart, HRB 14000;
Aufsichtsratsvorsitzender: Franz Fehrenbach; Geschäftsführung: Dr. Volkmar Denner,
Prof. Dr. Stefan Asenkerschbaumer, Filiz Albrecht, Dr. Michael Bolle, Dr. Christian Fischer,
Dr. Stefan Hartung, Dr. Markus Heyn, Harald Kröger, Rolf Najork, Uwe Raschke
​
Von: Pierre R. Mai <notifications@github.com>
Gesendet: Montag, 8. März 2021 11:00
An: OpenSimulationInterface/open-simulation-interface <open-simulation-interface@noreply.github.com>
Cc: Schoen Helmut (CR/AEL1) <Helmut.Schoen@de.bosch.com>; Author <author@noreply.github.com>
Betreff: Re: [OpenSimulationInterface/open-simulation-interface] Correct typos in model_reference comments in osi_groundtruth.proto (#493)


@pmai approved this pull request.

Seem obvious fixes that should be included ASAP.

**Review by ThomasNaderBMW — APPROVED** [review]
Makes totally sense!

**Comment by stefancyliax** [comment]
Review in OSI CCB:
- Can be merged
- DCO has to be done (@pmai @hschoen Can one of you do this, please?)

**Comment by hschoen** [comment]
How do I do the DCO?

Mit freundlichen Grüßen / Best regards

Helmut Schoen
CR/AEL1

Tel. +49 711 811-10880 | Mobil +49 173 9187997 | Threema Work<threemawork://add/?id=K286UVMU>: K286UVMU
​
Von: stefancyliax ***@***.***>
Gesendet: Mittwoch, 17. März 2021 11:11
An: OpenSimulationInterface/open-simulation-interface ***@***.***>
Cc: Schoen Helmut (CR/AEL1) ***@***.***>; Mention ***@***.***>
Betreff: Re: [OpenSimulationInterface/open-simulation-interface] Correct typos in model_reference comments in osi_groundtruth.proto (#493)


Review in OSI CCB:

  *   Can be merged
  *   DCO has to be done ***@***.***<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpmai&data=04%7C01%7Chelmut.schoen%40de.bosch.com%7C7f3ae12bdc1648decac108d8e92cf90f%7C0ae51e1907c84e4bbb6d648ee58410f4%7C0%7C0%7C637515726663922557%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=76INg30UAc8RBwxHsqiexv%2FKCR2DwScXtGr%2Fn%2FCUN00%3D&reserved=0> @hschoen<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhschoen&data=04%7C01%7Chelmut.schoen%40de.bosch.com%7C7f3ae12bdc1648decac108d8e92cf90f%7C0ae51e1907c84e4bbb6d648ee58410f4%7C0%7C0%7C637515726663932512%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4EnF3hctEJrS9Q2pdrg%2FF0nPIQpVsygV8P0k4k9c%2Foo%3D&reserved=0> Can one of you do this, please?)

**Comment by stefancyliax** [comment]
@hschoen Don't worry, Pierre is handling this right now.

**Comment by pmai** [comment]
> 
> 
> @hschoen Don't worry, Pierre is handling this right now.

Will do so. For future reference, the DCO check itself gives usually good instructions on how to fix a missing DCO after the fact if you look at the Details link of the failed check, e.g. here  https://github.com/OpenSimulationInterface/open-simulation-interface/pull/493/checks?check_run_id=2055400118

For this PR which is only a single commit, it would suggest to `git commit --amend --no-edit --signoff` and then doing a force push with `git push --force-with-lease master patch-1`; for more complex pull requests it would suggest doing a git rebase --signoff etc. and a force push.

**Pull request merged**
