### PR TITLE
Draft for discussion: Added element tricycle

### PR DESCRIPTION
**Pull request by FlorianMueller87**
﻿#### Reference to a related issue in the repository
Issue: #639

#### Add a description
ASAM OSI and ISO 23150 or AUTOSAR ADI have a common history. Unfortunately, the inner structure, the naming and the definitions of the standards are differentiated from each other. This makes the work of developers unnecessary complicated for mostly no technical reasons. All sides should strive to reduce inequality.

ASAM OSI need the entry TYPE_TRICYCLE for osi_objects – MovingObject - VehicleClassification – Type to be compatible with AUTOSAR ADI PotentiallyMovingObjectClassificationType.

#### Take this checklist as orientation for yourself, if this PR is ready for the Change Control Board:
- [x] My suggestion follows the [style and contributors guidelines](https://opensimulationinterface.github.io/osi-documentation/open-simulation-interface/doc/howtocontribute.html).
- [x] I have taken care about the [documentation](https://opensimulationinterface.github.io/osi-documentation/open-simulation-interface/doc/commenting.html).
- [x] I have done the [DCO signoff](https://opensimulationinterface.github.io/osi-documentation/open-simulation-interface/doc/howtocontribute.html#developer-certification-of-origin-dco).
- [x] My changes generate no errors when passing CI tests. 
- [ ] I have successfully implemented and tested my fix/feature locally.
- [ ] Appropriate reviewer(s) are assigned.

#### Additional context

ISO23150:2021 A.76 Enumeration: Potentially moving object classification type

@ThomasNaderBMW @jdsika @schmidtlorenz

### CODE REVIEW

**Comment by jdsika** [comment]
Questions:
* The first thing coming to mind is "what is the definition of a tricycle"? Is it the one from WW2 where we have a motorbike with a side car or is it rather a chrildrens toy?
* If AUTOSAR sees the need for this type could you also provide their proper defintion, please?
* The TRUCKS e.g. already have some pictures but most of the defintions are also lacking precision in description which needs further refinement (does AUTOSAR have some nice definitions there as well?)

Apart from these remarks I do not see a reason to not include this suggestion.

**Comment by thempen** [comment]
Harmonization discussion: 
"What is a tricycle?"
- With or without motor?
- Bike with three wheels
- TukTuk
- Motorbike with side car
- Trike
- Vehicles with closed wheels (front/back)

Please clarify it in more detail.

**Comment by jdsika** [comment]
Clarification:
* We are currently all compliant with ISO23150 as the ENUMS in the document are just examples. 
* Opinion: If the ISO provides examples it should make them with the good practice of defining it well and giving an argumentation formthe need
* If ADI has a stakeholder with a clear need for a definition then we are happy to discuss it.

**Comment by thempen** [comment]
OtherModels and Harmonization feedback: Closed. 

Basically it would be a good approach to harmonize all OpenX standards according to vehicle types. E.g. to avoid problems with traffic signs targeting some vehicle type group, and the vehicle types of OSI.

If needed, reopen, or create new PR with further description and reference this PR.

**Pull request closed without merging**
