### PR TITLE
Update github actions for release workflow

### PR DESCRIPTION
**Pull request by pmai**
﻿

### CODE REVIEW

**Review by florianwallerer — APPROVED** [review]
Looks fine :)

**Comment by florianwallerer** [comment]
Hi @philipwindecker can you also review this wit a more detailed look and with more knowledge than I have.

**Comment by philipwindecker** [comment]
> Hi @philipwindecker can you also review this wit a more detailed look and with more knowledge than I have.

I can take a look tomorrow. However, I am also quite busy with multiple topics right now, so it might slip to Friday if push comes to shove.

**Comment by florianwallerer** [comment]
> > Hi @philipwindecker can you also review this wit a more detailed look and with more knowledge than I have.
> 
> I can take a look tomorrow. However, I am also quite busy with multiple topics right now, so it might slip to Friday if push comes to shove.

Is not time pressing. We have time until the next CCB. Monday 2024-01-29

**Review by philipwindecker — APPROVED** [review]
Changes work fine in fork. PR approved.

**Comment by philipwindecker** [comment]
Question: Do related issues/branches/PRs exist for the other repos? They also use some of these actions and may even run on older version of Ubuntu (image). If so, please link them here in the PR description for reference.

**Review by jdsika — COMMENTED** [review]
Reviewed for v3.7.0

**Pull request merged**
