### PR TITLE
Add travis yaml

### PR DESCRIPTION
**Pull request by mbinna**
This config file causes Travis CI to build this project with a matrix
build job. More information:

* https://docs.travis-ci.com/user/languages/cpp
* https://genbattle.bitbucket.io/blog/2016/01/17/c++-travis-ci/?

### CODE REVIEW

**Comment by mbinna** [comment]
Hmm, I need to have a deeper look into the documentation of Travis. I'll update this pull request later.

**Comment by cmuck** [comment]
The build fails due to the CMake minimum required version 3.7.
Travis CI build machines are based on Ubuntu 12.04 LTS 64 bit.

**Comment by mbinna** [comment]
Sorry for the many commits. Travis CI is really picky regarding CMake and protobuf due to its old Ubuntu version.

**Comment by mbinna** [comment]
Now the pull request is ready to be discussed. Let me know if you are satisfied with the changes.

**Comment by mbinna** [comment]
Thank you, @pmai. I already discussed with @cmuck about how to get rid of the need to use sudo in Travis. This would reduce the startup time of the Travis build environment a lot. He or I might create a separate pull request.

**Comment by CarloVanDriestenBMW** [comment]
This closes #8

**Pull request merged**
