### PR TITLE
solution for issue #86

### PR DESCRIPTION
**Pull request by haoyuanying**
The issue #86 is solved. The detailed solution can be found in the attachment in the comments.

### CODE REVIEW

**Comment by CarloVanDriestenBMW** [comment]
Different timestamps in OSI:

Environment: Possible change to GPS time because of synchronization with DGPS in measurement run
Note "Schaltsekunde" in doxygen

Simulation time:
Needed: Sensor Start Offset in configuration which is always calculated from 0 on 
Simulation Starttime needs a proper definition
tbd: Reference a valid definition for Sceanario?

**Comment by CarloVanDriestenBMW** [comment]
add field simulation_starttime

**Comment by pmai** [comment]
I have added the relevant fields (offset and start time) to the configuration messages in PR #120. It is unclear to me whether we should conflate the idea of multi-scenario runs with simulation start and stop-times, since ideally sensor models should not be aware of a concept like scenario...

**Comment by CarloVanDriestenBMW** [comment]
@pmai yes I think the sensor model should not be aware of the scenario concept. You can close this pull-request with the merge of #120

**Comment by haoyuanying** [comment]
@pmai @CarloVanDriestenBMW I would say to have such a function actually turn on the possibility to actively simulate the fault cases in sensors, e.g. at a certain period of the time, due to environment / unknown conditions, the sensor is temperorilly out of order...

**Comment by pmai** [comment]
@haoyuanying that would require hard-coding/configuring the times into the sensor models for each scenario, which I think is not a good idea. This should IMHO be handled either through Special fault-injection models (which will have their own Parameters), or, if needed, flags into the sensor model to enable fault, etc., which would then be triggered by the scenario/simulation, right?

**Comment by haoyuanying** [comment]
@pmai Fault injection is one example. The idea to have the field also aims to help to crop a long scenario into sevaral smaller ones. I am not sure if to insert simulation start/ent time is easier than to re-create scenarios for simulator makers...

**Comment by pmai** [comment]
But what is the sensor model supposed to do with these times? Anything that depends on scenario data should IMHO not be known to the sensor model?

**Comment by haoyuanying** [comment]
@pmai In this case to separate these kind of information out of GT, do you think that it is valuable to make another field in OSI as SimulationConfiguration / SimulationControl?

**Comment by pmai** [comment]
@haoyuanying The question would be from where to where would these messages be communicated? I.e. who sends it, who receives it for what purpose? I think a number of extensions of OSI to cover more than the Environment Simulation -> Sensor -> Function use case would be beneficial (e.g. Function <-> Driving Dynamics <-> Environment Simulation), however I have not seen them tackled for now... Daimler would be fairly interested in these additions as well, as far as I gathered at the Ulm Workshop...

**Comment by haoyuanying** [comment]
@pmai I would also raise the question like this: if you use OSI only for data transfer, or you could use it for simulation toochain flow control (e.g. sensor feedback) as well, exactly like Function <-> Driving Dynamics <-> Environment Simulation...

**Comment by CarloVanDriestenBMW** [comment]
@pmai and @haoyuanying maybe we postpone this discussion to the next Pegasus meeting? I removed the milestone and we keep the pullrequest open.

**Comment by pmai** [comment]
@carsten-kuebler isn't this PR dead, i.e. we have the start time already in the sensor input configuration messages, and generally speaking we should be moving stuff that is static into a seperate setup message?

**Comment by CarloVanDriestenBMW** [comment]
@pmai I agree and will close this PR

**Pull request closed without merging**
