### PR TITLE
Add road surface texture (or fine roughness)

### PR DESCRIPTION
**Pull request by pmai**
This addresses issue #60 further, by including the surface texture or
fine roughness in addition to the surface_roughness field which is
indicating unevenness.

### CODE REVIEW

**Comment by CarloVanDriestenBMW** [comment]
@raueATconti can you comment on camera models here?

**Comment by hschoen** [comment]
Fine roughness and unevenness as I proposed are discussed in the following dissertation. However, the definition of unevenness there slightly deviates from IRI, but I suppose they are compatible.
**[Robert Schneider, „Modellierung der Wellenausbreitung für ein bildgebendes Kfz-
Radar“, Dissertation, Universität Karlsruhe, Mai 1998.](https://publikationen.bibliothek.kit.edu/24298)**
This quote may be used in the source code comment for fine roughness. For unevenness I agree that IRI is rather the standard.

**Comment by martin-fzd** [comment]
What is the intended use of road surface? Do you think of a (piecewise) definition of the road ahead?
 I'm asking as I wonder how to handle transitions between different road conditions efficiently...

**Comment by pmai** [comment]
@martin-fzd I think for now (i.e. for phenomenological models) that's likely the way to go, i.e. if you need changing road conditions (water, different texture, ...) you need to model that as a new lane. Having multiple conditions for the same lane, with switch-over points seems fairly complex, for little gain, since we need actual models using e.g. road textures and ray tracing or similar to handle road conditions more realistically.

**Comment by pmai** [comment]
I'll merge this change for now, with the added quote, since the overall discussion of how to handle changing road conditions goes beyond the current PR.

**Pull request merged**
