### PR TITLE
Added Date to EnvironmentConditions (solves #321)

### PR DESCRIPTION
**Pull request by ndunningbmw**
Issue: #321 

Changes made:
* Created Date message based on UNIX time
* Added Date to EnvironmentConditions and adjusted Field Numbers

### CODE REVIEW

**Comment by CarloVanDriestenBMW** [comment]
@ndunningbmw can you add the proper refernce to ISO 8601, please? why do you think should we keep the TimeOfDay message? "It is recommended" is kind of missing the "why", or?

**Comment by pmai** [comment]
If this should go into the next minor release of OSI (i.e. OSI 3.2) then the fields cannot be renumbered, since this breaks backward compatibility. Only for OSI 4.0 would renumbering be possible.

The description of the date message seems a bit unclear, since it is not totally clear whether the time expressed is the UTC time, or some local time. Theoretically speaking it should probably use UT1 instead of UTC, but practically speaking UTC should be near enough at all times for these kinds of calculations.

The near duplication with time of day is somewhat unlucky, so maybe time of day should be deprecated, and enough information in environment should be provided so that local time can be derived from the provided UTC (e.g. providing timezone offset).

**Comment by CarloVanDriestenBMW** [comment]
@ndunningbmw better like this?

**Comment by ndunningbmw** [comment]
> If this should go into the next minor release of OSI (i.e. OSI 3.2) then the fields cannot be renumbered, since this breaks backward compatibility. Only for OSI 4.0 would renumbering be possible.

I don't see why we can't wait until OSI 4.0.0, as this is not a urgent change but it is an necessary one.

> The description of the date message seems a bit unclear, since it is not totally clear whether the time expressed is the UTC time, or some local time. Theoretically speaking it should probably use UT1 instead of UTC, but practically speaking UTC should be near enough at all times for these kinds of calculations.

Can you explain why UT1 would be a better alternative?

> The near duplication with time of day is somewhat unlucky, so maybe time of day should be deprecated, and enough information in environment should be provided so that local time can be derived from the provided UTC (e.g. providing timezone offset).

I agree that it is not the best situation, but if the global position of the parent frame cannot be derived from the positional data, being able to still capture the local time is vital to some of the functionallity OSI is enabling.

**Comment by CarloVanDriestenBMW** [comment]
@ndunningbmw like this? I removed the Date message because there is just one global time UTC and there might me multiple TimeOfDay (in theorie). Is the note ok?

**Comment by CarloVanDriestenBMW** [comment]
@pmai I am getting the feeling that the unix_timestamp could also be part of the GroundTruth?

**Comment by CarloVanDriestenBMW** [comment]
@ainar You opinon is also welcome :)

**Pull request merged**
