### PR TITLE
Build: Create a release pipeline that replaces the manual creation of a deliverable package

### LINKED ISSUE #677: Build: Create release pipeline
#### Describe the feature
Right now, the release process involves manual steps to create the deliverables package offline and then upload it.
This can be integrated directly into GitHub as a new pipeline.

#### Describe the solution you would like
Ideally, the release of a new OSI version is nothing more than the press of a button.
Since there are more steps involved, the first improvement over the current process will be to automate the step of creating a new deliverables package.
The proposed solution is to convert the release steps from the (ASAM-internal) [local build repository](https://code.asam.net/simulation/osi-group/osi-local-build) and apply them as a GitHub pipeline. 

The pipeline is to run both for full and pre-releases.
This way, release candidates can be shared with decision makers, thus utilizing the automated build process. 

#### Describe alternatives you have considered
The manual steps could be kept, of course. 
Alternatively, an independent repository (such as the generator or a new one) could be responsible for handling these steps.
However, they do not seem as elegant.

#### Describe the backwards compatibility
This only impacts the build and release steps and, therefore, does not impact the backwards compatibility of its content whatsoever.

### PR DESCRIPTION
**Pull request by philipwindecker**
﻿#### Reference to a related issue in the repository
#677 

#### Add a description
Resolves #677 

#### Take this checklist as orientation for yourself, if this PR is ready for the Change Control Board:
- [x] My suggestion follows the [style and contributors guidelines](https://opensimulationinterface.github.io/osi-antora-generator/asamosi/latest/specification/contributing/start_contributing.html).
- [x] I have taken care about the [message documentation](https://opensimulationinterface.github.io/osi-antora-generator/asamosi/latest/specification/contributing/commenting_messages.html) and the [fields and enums documentation](https://opensimulationinterface.github.io/osi-antora-generator/asamosi/latest/specification/contributing/commenting_fields_enums.html).
- [ ] I have done the [DCO signoff](https://opensimulationinterface.github.io/osi-documentation/open-simulation-interface/doc/howtocontribute.html#developer-certification-of-origin-dco).
- [x] My changes generate no errors when passing CI tests. 
- [ ] I have successfully implemented and tested my fix/feature locally.
- [x] Appropriate reviewer(s) are assigned.

If you can’t check all of them, please explain why.
- This fix can only be tested through the GitHub CI.

If all boxes are checked or commented and you have achieved at least one positive review, you can assign the label ReadyForCCBReview!

## Related PRs
- https://github.com/OpenSimulationInterface/osi-antora-generator/pull/3
- https://github.com/OpenSimulationInterface/osi-sensor-model-packaging/pull/92
- https://github.com/OpenSimulationInterface/osi-documentation/pull/63

### CODE REVIEW

**Comment by philipwindecker** [comment]
DCO missing since the changes were mostly committed through the GitHub interface directly.

The history is too long since there was a lot of trial-and-error. Please merge with squashing commits, if possible.

**Comment by philipwindecker** [comment]
Fixed the DCO signoff

**Comment by philipwindecker** [comment]
As dicussed in today's CCB meeting, I removed the workarounds pointing to forked repositories.
Changes can now be merged. Please add review so I can proceed, @pmai .

Note that I will need to confirm operation after merge to make sure all changes work as intended here as well.

**Review by pmai — APPROVED** [review]
Approved as per CCB 2023-03-27

**Pull request merged**
