### PR TITLE
Detected... message references sensors (issue #147)

### PR DESCRIPTION
**Pull request by carsten-kuebler**
This PR adress issue #147 

Add a list of sensor ids to all Detected... messages. These sensors confirm this Detected... 'object'. It is a redundant info.

### CODE REVIEW

**Comment by pmai** [comment]
Rebased onto master for merging.

**Comment by CarloVanDriestenBMW** [comment]
@carsten-kuebler I guess I don't get the fact why it should be redundant:
You have a logic model which does the sensor fusion from two previously generated SensorData messages. The LM creates a new SensorData message which points to the same groundTruth (Both inputs might have this in common because otherwise one had to merge the GT messages). This new SD message now has detectedObjects with a new repeated ID which holds the IDS of the sensor models from which the input messages came and the overall SD ID refers to the ID of the LM?

**Comment by carsten-kuebler** [comment]
@CarloVanDriestenBMW It is redundant because you can determine the Sensor ID list 'SD_L' for a Detected... entity 'E' from the SensorData detection list list 'D_L_L'. 
For each Detection 'D' in 'D_L_L' with 'D'.object_id == 'E'.id: determine 'D' 's sensor mounting position 'MP' (take the 'MP' from the header of the detection list), determine sensor's ID 'S_ID' from 'MP' ('MP' is unique for one sensor), add 'S_ID' to 'SD_L' (if 'S_ID' is not present in 'SD_L').

With this algorithm you can generate the sensor ID list.

Yes, it is very time consuming and inefficient...

**Comment by pmai** [comment]
@carsten-kuebler @CarloVanDriestenBMW  I've rebased to current master, to solve the merge conflicts. Please reset --hard after fetching if you want to continue work on this branch (besides merging, which can happen as is).

**Comment by CarloVanDriestenBMW** [comment]
@carsten-kuebler as we discussed in the workshop. We will remove the comment about the redundancy and explain the purpose of this field regarding objects when no detection is available

**Comment by carsten-kuebler** [comment]
@pmai I made a second PR #161

**Pull request closed without merging**
