### PR TITLE
Make exclusion of side mirrors for vehicle bounding boxes clearer 

### PR DESCRIPTION
**Pull request by clemenshabedank**
#### Reference to a related issue in the repository
Add a reference to a related issue in the repository.
https://github.com/OpenSimulationInterface/open-simulation-interface/issues/444

#### Add a description
Add a description of the changes proposed in the pull request.
It was discussed that for Version 3.3 the side mirrors stay excluded of a vehicle's bounding box to ensure backward compatibility. For Version 4.0, the definition of a bounding box is expected to change. 

**Some questions to ask**:
What is this change? 
-> Make documentation better
What does it fix?
-> Inconsistency of a vehicle's bounding box (image needs to be changed)
Is this a bug fix or a feature? Does it break any existing functionality or force me to update to a new version?
How has it been tested?
-> bug fix, doesn't break 

#### Mention a member
Add @mentions of the person or team responsible for reviewing proposed changes.
@HendrikAmelunxen 
@thempen 
@kmeids 
@TimFrickeBMW
@ThomasNaderBMW 

#### Check the checklist

- [x] My code and comments follow the [style guidelines](https://opensimulationinterface.github.io/osi-documentation/osi/commenting.html) and [contributors guidelines](https://opensimulationinterface.github.io/osi-documentation/osi/howtocontribute.html) of this project.
- [x] I have performed a self-review of my own code.
- [x] I have made corresponding changes to the [documentation](https://github.com/OpenSimulationInterface/osi-documentation).
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests / travis ci pass locally with my changes.

### CODE REVIEW

**Comment by clemenshabedank** [comment]
Hello @paagkame, 
in the Harmonization meeting with @HendrikAmelunxen yesterday we have decided that in the picture https://opensimulationinterface.github.io/open-simulation-interface/structosi3_1_1BaseMoving.html the grey dashed (bounding) box shall **not** surround the side mirrors. This is then consistent to the current desription in the base attribute of MovingObject "The bounding box does NOT includes mirrors for vehicles." A bigger revision for the bounding box concept is planned to be undertaken for V4.0. 
May you assist with changing the picture? Thank you!

**Comment by paagkame** [comment]
@clemenshabedank 
What do you thing of this?
OSI_BaseMoving

Without coloring the car, it would not be so clear.

**Comment by clemenshabedank** [comment]
I like this!

**Comment by paagkame** [comment]
@clemenshabedank 
Here is a suggestion for a top view. I think we should paint the car inside the bounding box as well in grey, to be consistent and differentiate between mirrors and the rest of the car body. What do you think?
OSI_BaseMoving_top

**Comment by clemenshabedank** [comment]
yes, that looks very good and with consistent color it will even be better! Both pictures next to each other should make the exclusion of side mirrors and the 3D-aspect of a bounding box very clear in my opinion.

**Comment by paagkame** [comment]
@clemenshabedank 
I have colored the car and added the file OSI_BaseMoving_Top.svg to the branch.
I am not quiet sure where to add the svg to the to make it visible in the reference documentation at https://opensimulationinterface.github.io/open-simulation-interface/structosi3_1_1BaseMoving.html
Can you help me with that?

**Comment by paagkame** [comment]
I forgot to sign off my first commit. Can I add the singoff afterwards?

**Comment by clemenshabedank** [comment]
Not really, I think. 
All I know is that it is referenced from osi_common.proto, line 348: 
`// \image html OSI_BaseMoving.svg`
To me it appears that this is displayed in the reference documentation. But I dont really know how the reference documentation is build/rendered from the proto files.

**Comment by paagkame** [comment]
Thanks that helped already. I just wasn't sure which file I have to edit. So I added a line to include the image with the top view just after the 3D model.

@clemenshabedank  
Please review and approve if that is OK for you.

**Comment by clemenshabedank** [comment]
@paagkame yes that should be correct. Probably that way it will be displayed in the reference documentation for BaseMoving which is what we want.

**Comment by kmeids** [comment]
**Output from CCB meeting - 20.01.2021**
Actions:
1. @clemenshabedank could you please merge this?

**Review by kmeids — APPROVED** [review]
Agreed upon in  CCB meeting - 20.01.2021

**Comment by clemenshabedank** [comment]
Hello @paagkame I merged this PR, though it looks to me that the new pictures are not visualized in the reference documentation. Do you know if there is an automatic build system behind that which might be broken or if something has to be done manually?

**Comment by clemenshabedank** [comment]
@paagkame Now, the reference documentation is updated, so there only seemed to be a delay through the build system. So nothing else to do here :)

**Pull request merged**
