### PR TITLE
Units correctly written in osi_common.proto.

### PR DESCRIPTION
**Pull request by PhRosenberger**
#### Reference to a related issue in the repository
Part of the solution for #362.

#### Add a description
Changes the first file "osi_common.proto" so that documentation has the correct unit-writing in the comments.

**Some questions to ask**:
It is only part of the complete bug fix for the documentation, to be clarified before more action on all files is taken.
The question is now, if it is fine like this, before I continue.

#### Mention a member
@jdsika should know the problem from our conversation about it on telephone.

#### Check the checklist

- [x] My code and comments follow the [style guidelines](https://opensimulationinterface.github.io/osi-documentation/osi/commenting.html) and [contributors guidelines](https://opensimulationinterface.github.io/osi-documentation/osi/howtocontribute.html) of this project.
- [x]  I have performed a self-review of my own code.
- [x] I have made corresponding changes to the [documentation](https://github.com/OpenSimulationInterface/osi-documentation).
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests / travis ci pass locally with my changes.

### CODE REVIEW

**Comment by jdsika** [comment]
Link new document as refernce to the OSI documentation in the commenting section regarding units.

**Comment by jdsika** [comment]
The corresponding PR should be mnade for the docu repo

**Comment by jdsika** [comment]
I recommend a branch because of the CI

**Comment by PhRosenberger** [comment]
Doing is confirmed, PR will be closed and changes will be part in a complete PR for whole docu later.

**Pull request closed without merging**
