### PR TITLE
Add lane driving direction to the message lane (#84)

### PR DESCRIPTION
**Pull request by solosito**
This is the first approximation to the lane driving direction. It is not ready to be merged. First has to be analysed and discussed as described in the issue #84

### CODE REVIEW

**Comment by CarloVanDriestenBMW** [comment]
Thank you for your contribution. I would like to take some time for a review and discuss it with the tool developer.

**Comment by CarloVanDriestenBMW** [comment]
> This is the line, that a typical vehicle is supposed to follow. Thus, if the road narrows (e.g. construction site) this line is supposed to describe the trajectory that the vehicle should follow. **The intended direction of travel on the lane is given by the direction defined by the sequence of points forming the center line.**

This comment in osi:lane center_lane has to be updated then?

**Comment by solosito** [comment]
> This comment in osi:lane center_lane has to be updated then?

Actually yes. It should specify that the intended driving direction it is not described by the center_line but by the lane_driving_direction.

**Comment by CarloVanDriestenBMW** [comment]
Hi @solosito ,
we considered your feedback and will introduce a lane driving direction in the OSI 2.3.0 release on Jan. 26th. We would consider using a vector3d in order to describe the direction. Would this be suitable for you?
Best regards
Carlo

**Comment by solosito** [comment]
Hallo @CarloVanDriestenBMW ,
I think it is a good idea using a vector3d rather than using a flag. The driving direction could be defined more precisely.
Best regards,
Alfonso.

**Comment by AndreHildebrandt** [comment]
Hello @CarloVanDriestenBMW,

I think, that a Vector3D alone would not be sufficient. One would need either a second vector3D or an orientation3D IMHO.
Example: A hairpin curve. The IntendedDrivingDirection is then depending on the position of the vector3D. One needs a point of reference and a driving direction.

Best wishes,
Andre Hildebrandt

**Comment by solosito** [comment]
Hi again,

then the initial suggestion of having a flag is a very good option. There is no need to have a tangential vector of the curve to know which is the intended driving direction as the curve itself contains that information. It is only necessary to know whether the intended driving direction follows the points' storing order or its reverse. 

Thus, in case of conversions from left- to right-hand traffic and vice-versa, it would be as simple as changing this flag to the proper value.
___
@AndreHildebrandt 
> Apart from that, there has been the suggestion to replace the successor and predecessor lane ids by LaneConnectionPair ids. Do they implicitly define the intended driving direction?

 No. What would be the intended driving direction in case of having just a single lane with a permanent id?

**Comment by carsten-kuebler** [comment]
At the OSI workshop in Ulm (2017) there was a discussion to add a driving direction. But that does't suit as @AndreHildebrandt mentioned. Therefore you have to specify start point and driving direction or a flag as proposed from @solosito. 
Bidirectional lanes or small lanes require 2 center lines and there is no left and right. So I proposed #110.

**Comment by CarloVanDriestenBMW** [comment]
@solosito is the following solution ok for you? You can find it in #110

`optional bool center_line_is_driving_direction = 4;`

**Comment by CarloVanDriestenBMW** [comment]
@pmai there are some new comments in #110 - I will close the issue and you can merge the comments.

**Pull request closed without merging**
