### PR TITLE
Add lane sub-types to represent OpenDRIVE lane type information

### PR DESCRIPTION
**Pull request by pmai**
This is an interim solution used in the SETLevel4To5 project for lane type information from OpenDRIVE coordinated with ASAM to allow for e.g. pedestrian model implementation.

- [x] My code and comments follow the [style guidelines](https://opensimulationinterface.github.io/osi-documentation/osi/commenting.html) and [contributors guidelines](https://opensimulationinterface.github.io/osi-documentation/osi/howtocontribute.html) of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the [documentation](https://github.com/OpenSimulationInterface/osi-documentation).
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests / travis ci pass locally with my changes.

Signed-off-by: Pierre R. Mai <pmai@pmsf.de>

### CODE REVIEW

**Comment by jdsika** [comment]
@HendrikAmelunxen please make sure to add your company email address to your private github account. Use this email to commit and in addition "sign" a message as described in the documentation (e.g. click on details in failed DCO action). This is an additional quality gate introduced lately. Best regards, Carlo

**Comment by clemenshabedank** [comment]
Ich denke es müssen noch Bilder und die Beschreibung daneben unter https://opensimulationinterface.github.io/open-simulation-interface/structosi3_1_1Lane_1_1Classification.html angepasst werden.
lb11 ist ja keine free lane boundary mehr und die lane boundaries der Fußgängerwege sollten aus meiner Sicht noch eingezeichnet werden.

**Comment by kmeids** [comment]
Output from CCB meeting - 25.11.2020

Actions:

@HendrikAmelunxen to organize a follow-up meeting regarding the centerline definition and its involvement with other lane types.

**Comment by HendrikAmelunxen** [comment]
The harmonization workinggroup decided not to touch the centerline definition for non-drivable lanes.
Reasons:
•	Would result in significant increase of data
•	Centerline can be deduced based on the laneboundaries
•	The centerline concept should be revised for the next major release 

Therefore I set the label "Ready for CCB"

**Comment by kmeids** [comment]
**Output from CCB meeting - 09.12.2020**
Actions:
1. @max-rosin to perform documentation review.

**Comment by paagkame** [comment]
@pmai 
linguistic review is done. If changes are OK for you, please merge.

**Review by kmeids — APPROVED** [review]
CCB approved.

**Pull request merged**
