### PR TITLE
Remove RelevantLane and RelevantDirection in Detected...

### PR DESCRIPTION
**Pull request by carsten-kuebler**
Remove RelevantLane and RelevantDirection.
Relevant lanes and directions are defined in Candidate... assigned_lanes and traffic light's icons.

### CODE REVIEW

**Comment by CarloVanDriestenBMW** [comment]
Question:
I think how I understand these fields now, they represent the "best guess" of the sensor on what it thinks is the assoziated lane and not the lane it is actually assigned to!

**Comment by carsten-kuebler** [comment]
Yes. Would you leave the associated_lane_id(s) empty? I would use associated_lane_id(s) as a best guess of the sensor...

**Comment by CarloVanDriestenBMW** [comment]
@carsten-kuebler where is the "associated_lane_id" ? So:

The sensor has a "detectedLane" and a "DetectedTrafficSign" and within the sign we have an associated_lane_id ?

**Comment by carsten-kuebler** [comment]
Yes in the standard case (all referenced IDs are "local" in a SensorData message/message sequence). 

Could there be also the case that there are HD maps and these are used/referenced by the DetectedTrafficSigns?

**Comment by CarloVanDriestenBMW** [comment]
hm good question!
the map data and the detected lane would be merged by the sensor and the (also) merged traffic sign in the map would be assoziated with the (newly fused) detected lane?

**Comment by carsten-kuebler** [comment]
It is easier to remove the messages and avoid the merge...

**Comment by CarloVanDriestenBMW** [comment]
@carsten-kuebler I think we need the relevant lane and reference the DetectedLanes in here. The relevant direction is redundant because of the icon AND the fact that the association with a specific lane gives the direction relevance.

**Pull request merged**
