### PR TITLE
Point order of centerline and lane bounaries

### PR DESCRIPTION
**Pull request by clemenshabedank**
#### Reference to a related issue in the repository
https://github.com/OpenSimulationInterface/open-simulation-interface/issues/411

#### Add a description
The order of points describing the centerline and the lane bounaries is defined with a number of advantages as @TimFrickeBMW states in the mentioned issue: 
(+) Doubling of the middle-line can be avoided in cases like the one above
(+) Valid for lanes without explicit driving direction, e.g. non-driving lanes (or even all lanes in GroundTruth in my opinion)
(+) Follows same approach as OpenDrive

It has to be decided if the advantages weigh stronger than the risks and if this change can be for V3.3 or has to be postponed for V4.0. Risks (summarized by @TimFrickeBMW in the same issue):
(-) Loss of backwards compatibility. I do not regret that much because I find the current definition slightly flawed.
(-) Loss of intuitiveness. I think the "intuitiveness" of the current definition gives everyone a false sense of security, as if nothing could be misunderstood. What if my sensor moves against the "intended driving direction" during some overtaking maneuver? All of a sudden left and right change sides and no one has anticipated it.

For more information, please read the issue.

**Some questions to ask**:
What is this change? 
-> Documentation changing semantics
What does it fix? 
-> improves error-prone concept
Is this a bug fix or a feature? Does it break any existing functionality or force me to update to a new version?
How has it been tested?
->  It is expected to improve the semantics and has an effect on interpretation of the data. Therefore it could break existing functionality.

#### Mention a member
Add @mentions of the person or team responsible for reviewing proposed changes.
@HendrikAmelunxen 
@tbleher
@TimFrickeBMW

#### Check the checklist

- [x] My code and comments follow the [style guidelines](https://opensimulationinterface.github.io/osi-documentation/osi/commenting.html) and [contributors guidelines](https://opensimulationinterface.github.io/osi-documentation/osi/howtocontribute.html) of this project.
- [x] I have performed a self-review of my own code.
- [x] I have made corresponding changes to the [documentation](https://github.com/OpenSimulationInterface/osi-documentation).
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests / travis ci pass locally with my changes.

### CODE REVIEW

**Comment by clemenshabedank** [comment]
@paagkame: is it possible to add this picture https://github.com/OpenSimulationInterface/open-simulation-interface/issues/411#issuecomment-738072372 (feel free to make it more beautiful) to the Detailed Desriptions of the reference documentation for Lane and LaneBoundary?

**Comment by paagkame** [comment]
@clemenshabedank  
Just to make sure I understand it correctly, you want to add the picture to the following to chapters of the reference documentation
- [lane](https://opensimulationinterface.github.io/open-simulation-interface/structosi3_1_1Lane.html)
- [lane boundaries](https://opensimulationinterface.github.io/open-simulation-interface/structosi3_1_1LaneBoundary.html)

I think the best place for the image is just after the first sentence. Do you agree?

About the image:
I would recommend to add something like a legend that explains the parts of the image.
- lb = lane boundary?
- cl = center line? 
- What does the numbered dots stand for?
- Can you provide me this image in an editable format, like SVG?

**Comment by clemenshabedank** [comment]
Hello @paagkame 

- yes that's what we had in mind. By looking at it again, I think the locations of the pictures should be slightly different, so in the same place where I put the \attention changes in the inline documentation ("notes", "attention" and "image" comments should be displayed in the reference documentation, if I understand it correctly). So the places for the picture would be: https://opensimulationinterface.github.io/open-simulation-interface/structosi3_1_1Lane_1_1Classification.html#a0085c16a3e1677daf76db0ad23d79e42 and https://opensimulationinterface.github.io/open-simulation-interface/structosi3_1_1LaneBoundary_1_1BoundaryPoint.html
- then we would also need the \image comments with the picture link in the inline documententation. I think the best place would be before the new \attention comments. 
- the legend currently seems to be handled by a \note comment below the image in many cases, so I could add a new note comment afterwards to keep it as consistent as possible with the other "legends". But I am not sure how consistent this is for whole OSI. I think this might be solved in another (maybe more consistent way) if you suggest that. 
- Your abbreviation assumptions are correct. The dots stand for the repeated Vector3D fields that represent the centerline or the lane boundaries, respectively. If this doesn't become clear after the changes, we should do more changes I think.
- @HendrikAmelunxen can you provide the image as @paagkame requests?

**Comment by HendrikAmelunxen** [comment]
Sure I can provide it.
It was a very quick sketch in Powerpoint to serve as basis for a disussion. 
@paagkame What format is best for you? I could provide it as ppt, or export it as a figure (gif, jpg, png, tif, bmp, emf, wmf).

**Comment by paagkame** [comment]
@HendrikAmelunxen 
The native format (ppt) would be perfect. Thanks

**Comment by HendrikAmelunxen** [comment]
@paagkame Here it is
[lane_example.pptx](https://github.com/OpenSimulationInterface/open-simulation-interface/files/5809867/lane_example.pptx)

**Comment by paagkame** [comment]
@clemenshabedank 
I edited the SVG a little bit to have a consistent style for those wireframed streetviews. Please let me know if you want to add for example the color of the street.
OSI_LaneBoundaries_And_CenterLine
I also added the lines to include the svgs as you mentioned and added already a note afterwards for explaining the abbreviations. Please have a look if that is what you had in mind.

**Comment by HendrikAmelunxen** [comment]
@paagkame I know that it was also in the original sketch, but I think the spacings between the dots have to be adjusted:
image

Referring to this part of the documentation, the discretization of lb1, lb3, cl1 and cl2 should be the same. I think it makes sense to adjust cl1 and cl2 to the discretization of lb1 and lb3. 

I think it would also be good to have the road colored in grey order to make it clearer that lb1, lb2 and lb3 are lines on the road.

**Comment by paagkame** [comment]
@HendrikAmelunxen 
I have made changes according to your suggestion. Please have a look at the result. I also rearranged parts of the SVG to get the focus on the cl and lb. I hope that was OK.
OSI_LaneBoundaries_And_CenterLine

**Comment by paagkame** [comment]
@clemenshabedank @HendrikAmelunxen 

One terminology-related question: The described centerline is different to the center lane described in the [Open DRIVE standard ](https://www.asam.net/index.php?eID=dumpFile&t=f&f=3495&token=56b15ffd9dfe23ad8f759523c806fc1f1a90a0e8#_lanes). The centerline in OSI defines the driving direction whereas the the center lane serves as reference for lane numbering. Did I understand that correctly?

**Comment by clemenshabedank** [comment]
Hello @paagkame, yes it is correct that those concepts have nothing in common. In OSI there exist a centerline for each driving lane and it is in the middle of each lane. In OpenDRIVE the center lane serves for lane numbering as you wrote.

**Comment by HendrikAmelunxen** [comment]
@paagkame Perfect, thanks!

**Comment by kmeids** [comment]
**Output from CCB meeting - 20.01.2021**
Actions:
1. @clemenshabedank this is ready to be merged.

**Review by kmeids — APPROVED** [review]
Agreed upon during the CCB meeting  - 20.01.2021

**Pull request merged**
