### PR TITLE
Add is_stationary convenience flag to Vehicle (#89)

### PR DESCRIPTION
**Pull request by pmai**
Convenience flag, needs discussion about whether we need something like this elsewhere.

### CODE REVIEW

**Comment by CarloVanDriestenBMW** [comment]
default should be moving imo

**Comment by carsten-kuebler** [comment]
From standardisation (real sensors) activities point of view there is an enum DetectedObject::MovementState (see #117).

Simplified petri net for moving objects:

O --> stationary --> moving <--> stopped

**Comment by pmai** [comment]
So should we support the more expressive state (distinguishing between unknown, stationary and stopped vs. moving)? Given that this is GroundTruth, I'm not even sure we need the flag at all, but what is the opinion of the requesters (see issue #89), i.e. @HannesSchneiderAVL, @haoyuanying ?

**Comment by carsten-kuebler** [comment]
@pmai what is the benefit, if we specify in GT that a vehicle is temporary stationary? I see no benefit. Sensor(Output)Data can benefit from this information, because it's a local, temporary valid information.

**Comment by pmai** [comment]
If noone (@HannesSchneiderAVL, @haoyuanying ) of the original requesters comments on this, I'm going to drop the PR for now...

**Comment by haoyuanying** [comment]
@pmai @carsten-kuebler Would it be beneficial in terms of enhancing the performance to have the flag as a redundent index to check if the vehicle is temperorilly stationary if comparing to check velocities in X, Y, Z?

**Comment by pmai** [comment]
I don't think there will be any significant performance savings (i.e. transmitting another field in protobuf is likely to be much more exprensive than any simple x, y, z comparision (i.e. at most 3 substractions, 3 abs, 2 additions and 1 compare). And utility libraries can internally add this optimization on top for clients...

**Comment by HannesSchneiderAVL** [comment]
sorry for the late answer. We discussed this internally and came also to the conclusion that this could have performance issues, so we also see no need for this flag any more.

**Comment by pmai** [comment]
Closing PR for now due to lessened Need.

**Pull request closed without merging**
