### PR TITLE
Example images for documentation

### PR DESCRIPTION
**Pull request by carsten-kuebler**
Images in Lanes and Lane Boundaries.

### CODE REVIEW

**Comment by CarloVanDriestenBMW** [comment]
Comments for pictures:
1) OSI_BaseStationary.jpg, design (colors...etc), what kind of picture is there inside, base polygon is not understandable
2) Pictures in general: If I show the picture to a random person it needs all information necessary to understand the picutre.
3) Some images are duplicated

Requirements

**Comment by CarloVanDriestenBMW** [comment]
The images should be vector graphics.  [Positive Example](https://mediatum.ub.tum.de/doc/1325791/1325791.pdf)

**Comment by CarloVanDriestenBMW** [comment]
@carsten-kuebler merge conflict

**Comment by carsten-kuebler** [comment]
@CarloVanDriestenBMW please review the figures and documentation.

**Comment by carsten-kuebler** [comment]
@CarloVanDriestenBMW We leave some rendered images in the documentation, because the corresponding figures are missing at the moment. Mr. Schreiner could design new figures next year.

**Comment by CarloVanDriestenBMW** [comment]
@carsten-kuebler  still conflicting

yes, we can draft the images beginning of next year.

**Pull request merged**
