### PR TITLE
Bugfix osi trace

### PR DESCRIPTION
**Pull request by serge-m**
#### Reference to a related issue in the repository
https://github.com/OpenSimulationInterface/open-simulation-interface/issues/437

#### Add a description
Added test that fails without the fix, added the fix.
Trivial typo probably.

#### Mention a member
@carsten-kuebler @pmai  Could you please take a look?

#### Check the checklist

- [ ] My code and comments follow the [style guidelines](https://opensimulationinterface.github.io/osi-documentation/osi/commenting.html) and [contributors guidelines](https://opensimulationinterface.github.io/osi-documentation/osi/howtocontribute.html) of this project.
- [ ] I have performed a self-review of my own code.
- [x] I have made corresponding changes to the [documentation](https://github.com/OpenSimulationInterface/osi-documentation).
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests / travis ci pass locally with my changes.

### CODE REVIEW

**Comment by vkresch** [comment]
@serge-m  thanks for opening the PR. It is a good idea to create a unit test for the `osi2read.py` but instead of uploading a file how about if we generate it in the CI directly with [this](https://opensimulationinterface.github.io/osi-documentation/open-simulation-interface/doc/fileformat.html#generate-osi-traces) code?

**Comment by serge-m** [comment]
Hi @vkresch Thank you for the review. I tried to address those points.
I have now the build failing with another reason:


```
The command "doxygen" exited with 0.

0.00s$ cd ..

The command "cd .." exited with 0.

3.29s$ python3 -m unittest discover tests

......................E..

======================================================================

ERROR: test_osi_trace (unittest.loader._FailedTest)

----------------------------------------------------------------------

ImportError: Failed to import test module: test_osi_trace

Traceback (most recent call last):

  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path

    module = self._get_module_from_name(name)

  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name

    __import__(name)

  File "/home/travis/build/OpenSimulationInterface/open-simulation-interface/tests/test_osi_trace.py", line 5, in <module>

    from format.OSITrace import OSITrace

  File "/home/travis/build/OpenSimulationInterface/open-simulation-interface/format/OSITrace.py", line 9, in <module>

    from osi3.osi_sensorview_pb2 import SensorView

  File "/home/travis/build/OpenSimulationInterface/open-simulation-interface/osi3/osi_sensorview_pb2.py", line 6, in <module>

    from google.protobuf import descriptor as _descriptor

ModuleNotFoundError: No module named 'google'

----------------------------------------------------------------------

Ran 25 tests in 3.153s

FAILED (errors=1)

The command "python3 -m unittest discover tests" exited with 1.
cache.2

store build cache

Done. Your build exited with 1.
```

As far as I understand the package and it's dependency (`protobuf`) are not being installed in travis. 
I think the issue can be solved if I add `python3 setup.py install` or `python3 -m pip install .` in the travis config. Not sure if that is  a good solution. Could you please help with that?

**Comment by vkresch** [comment]
Yes you are right! Try adding `python3 -m pip install .` between [line 80 and 81](https://github.com/OpenSimulationInterface/open-simulation-interface/blob/master/.travis.yml#L80) and between [105 and 106](https://github.com/OpenSimulationInterface/open-simulation-interface/blob/master/.travis.yml#L105).

**Comment by serge-m** [comment]
It seems that there is a limited version of python3. It diesn't have `pip`:
```
The command "python3 setup.py sdist" exited with 0.

$ python3 -m pip install .

/usr/bin/python3: No module named pip

The command "python3 -m pip install ." exited with 1.

$ cd build
```
https://travis-ci.com/github/OpenSimulationInterface/open-simulation-interface/jobs/424963479#L937

**Comment by serge-m** [comment]
The tests pass now. I added python3-pip and python3-wheel as dependencies.

**Review by vkresch — APPROVED** [review]

**Pull request merged**
