### PR TITLE
Added ENU coordinate system specifications to HostVehicleData

### PR DESCRIPTION
**Pull request by u21n80**
﻿#### Related issue
Fixes point 3 of #445 regarding the missing information about the ENU coordinate system.

#### Description
- Moved vehicle location, coordinate system origin and rmse to toplevel as there is no need for an additional message. 
- Coordinate system of location and rmse has been clearly specified, if enu_origin is not specified then the old behavior where an arbitrary cartesian coordinate system is used, is restored. 
- Removed the raw Gnss sensor information as they shall be moved to a sensor specific message like it is the case for lidar measurements and images.

Signed-off-by: u21n80 <jonas.lai@avl.com>

### CODE REVIEW

**Comment by ThomasSchloemicherAVL** [comment]
@u21n80 can you please add a more meaningful title

**Comment by u21n80** [comment]
> @u21n80 can you please add a more meaningful title of this PR

Yes of course, seemed to be the auto-generated title and I forgot to change it. Done now.

**Comment by pmai** [comment]
Is there some overarching reason why this PR would renumber the fields, thus making it non-backward compatible? Especially since this now resorts back to the original fields, this change should be completely possible to release in 3.4.0 for example...

**Comment by u21n80** [comment]
> Is there some overarching reason why this PR would renumber the fields, thus making it non-backward compatible? Especially since this now resorts back to the original fields, this change should be completely possible to release in 3.4.0 for example...

Hi, no sorry I was unaware of that, I just changed the fields so that the order in the code is reflected here. I will change it back.

**Comment by ThomasNaderBMW** [comment]
@u21n80 : I transferred your points into the PR #441. What I left out is the definition on the top level.
For me it makes the HostVehicleData better to be understood as a restbussimulation (all information is on the same level and not taken out of the submessages). We can discuss this in the next meeting from @ThomasSchloemicherAVL

**Comment by jola6897** [comment]
@ThomasNaderBMW I made the type of the ENU origin now a message with explicit mention of longitude, latitude and altitude. The documentation is the same as your GeoreferencedInformation but I renamed it to GeodeticPosition.

Also I intend to reuse the location field (BaseMoving) to convey the information of position relative to the enu origin, but here also acceleration and velocity can be given. The coordinate frames of all values inside BaseMoving should be defined by the fact that I specify the parent frame of BaseMoving.

**Comment by ThomasNaderBMW** [comment]
> @ThomasNaderBMW I made the type of the ENU origin now a message with explicit mention of longitude, latitude and altitude. The documentation is the same as your GeoreferencedInformation but I renamed it to GeodeticPosition.
> 
> Also I intend to reuse the location field (BaseMoving) to convey the information of position relative to the enu origin, but here also acceleration and velocity can be given. The coordinate frames of all values inside BaseMoving should be defined by the fact that I specify the parent frame of BaseMoving.
> 
> @ThomasNaderBMW I would also recommend to merge this pull request instead of manually copying the text to the other branch to maintain traceability.

I updated my PR regarding your suggestions with smaller restructuring. I had to do it manually because of merge conflicts here, I think a rebase would have been necessary here.

**Comment by clemenshabedank** [comment]
CCB 09/05/2022: We close this because we think it was fixed by #547 . In case this is incorrect please object @u21n80 .

**Pull request closed without merging**
