### PR TITLE
Make CMAKE_CXX_STANDARD overridable (fix #741)

### LINKED ISSUE #741: Allow Setting CMAKE_CXX_STANDARD via Command Line in CMake
We at openPASS are planning to update protobuf to 3.22.0 or higher. However, for these versions of protobuf CMAKE_CXX_STANDARD 14 is required. But the CMAKELISTS.txt in open-simulation-interface hard-coded the CMAKE_CXX_STANDARD to 11. Therefore, it would be great if we there is an optional feature which also allows the user to set the CMAKE_CXX_STANDARD through command line.

### PR DESCRIPTION
**Pull request by pmai**
fixes #741

### CODE REVIEW

**Review by jdsika — APPROVED** [review]

**Comment by jdsika** [comment]
Can be closed as part of #758 ?

**Comment by jdsika** [comment]
OK, this is good to be merged!

**Comment by pmai** [comment]
CCB 2024-01-15: Merge as-is.

**Comment by jdsika** [comment]
Reviewed for v3.7.0

**Pull request merged**
