### PR TITLE
Add orientation rate to PedestrianAttributes::Bone

### PR DESCRIPTION
**Pull request by ClemensLinnhoff**
﻿#### Reference to a related issue in the repository
#747 

#### Add a description
Add orientation rate to the bone class. The translatory velocity of the bones can be calculated with the orientation rate of the parent bones.

#### Take this checklist as orientation for yourself, if this PR is ready for the Change Control Board:
- [x] My suggestion follows the [style and contributors guidelines](https://opensimulationinterface.github.io/osi-antora-generator/asamosi/latest/specification/contributing/start_contributing.html).
- [x] I have taken care about the [message documentation](https://opensimulationinterface.github.io/osi-antora-generator/asamosi/latest/specification/contributing/commenting_messages.html) and the [fields and enums documentation](https://opensimulationinterface.github.io/osi-antora-generator/asamosi/latest/specification/contributing/commenting_fields_enums.html).
- [x] I have done the [DCO signoff](https://opensimulationinterface.github.io/osi-documentation/open-simulation-interface/doc/howtocontribute.html#developer-certification-of-origin-dco).
- [x] My changes generate no errors when passing CI tests. 
- [x] I have successfully implemented and tested my fix/feature locally.
- [x] Appropriate reviewer(s) are assigned.

### CODE REVIEW

**Review by PhRosenberger — APPROVED** [review]

**Comment by pmai** [comment]
CCB 2024-01-29: Should be reviewed by @Peintnerer and @thempen, especially if also velocity should be added, as there is no directly specified relationship between position changes and hierarchical orientation_rate since we have no specified kinematic model (positions and hence gaps between bones can vary over time depending on modeling approaches). Therefore it might be a good idea to include velocity to provide all of the information the internal model has to consumers. To be re-revied at next CCB.

**Comment by ClemensLinnhoff** [comment]
We thought about it again and came to the conclusion, that also adding the translatory velocity makes sense, mainly because the shoulders and legs are disconnected from the spine. So there can be independent translatory movement.
And as you said, if positions and bone lengths can theoretically also vary over time, we definitely need it.

**Review by Peintnerer — APPROVED** [review]
I can definitely see that having information about the bone's velocity and orientation rate makes sense. This is probably dependent on the modeling approach or motion capture method used, but I can imagine a few applications in which this might come in handy.

**Review by PhRosenberger — APPROVED** [review]

**Comment by pmai** [comment]
CCB 2024-02-12: Decision merge as-is.

**Comment by jdsika** [comment]
reviewed for v3.7.0

**Pull request merged**
