### PR TITLE
Add host vehicle data as sensor input data

### PR DESCRIPTION
**Pull request by pmai**
This changeset introduces HostVehicleData which comprises all vehicle
internal data that is available to the sensors (or in the future other
parts of OSI) as additional input. This includes e.g. GPS-sensor derived
data as well as e.g. engine ECU data, etc.  For now this only includes
GPS-sensor location data with error estimation.

### CODE REVIEW

**Comment by martin-fzd** [comment]
Rather than GPS Data, I would advise to read Steering Wheel Angle, Wheel Speeds and Yaw Rather from the host vehicle, as these are more valueable for e.g. tracking algorithms.

**Comment by CarloVanDriestenBMW** [comment]
@martin-fzd I think the goal is to extend the message over time. With the current implementation it is more or less the output of a componente that estimates the host vehicles location. We can make that subject to the next pegasus meeting?

**Comment by martin-fzd** [comment]
Yes, please.

**Comment by CarloVanDriestenBMW** [comment]
@raueATconti can you add this to the agenda?

**Pull request merged**
