### PR TITLE
832 consolidate hosted osi documentation sources

### LINKED ISSUE #832: Consolidate Hosted OSI Documentation Sources
#### Describe the bug

Currently, there are three separate sources for OSI documentation hosted online:

- The main Antora documentation at: [opensimulationinterface.github.io/osi-antora-generator](https://opensimulationinterface.github.io/osi-antora-generator)
- The OSI v3.5.0 Antora documentation at: [opensimulationinterface.github.io/osi-documentation/](https://opensimulationinterface.github.io/osi-documentation/)
- The Doxygen documentation at: [https://opensimulationinterface.github.io/open-simulation-interface/](https://opensimulationinterface.github.io/open-simulation-interface/)

#### Describe how to reproduce the bug
1. Visit the links mentioned above.
2. Observe that the documentation is split across three sources.

#### Describe the expected behavior

A unified and streamlined documentation experience. Specifically, the following changes are recommended:

- Remove the dedicated hosting for the OSI v3.5.0 documentation.
- Redirect [opensimulationinterface.github.io/osi-documentation](https://opensimulationinterface.github.io/osi-documentation/) to point to the latest version hosted at [opensimulationinterface.github.io/osi-antora-generator](https://opensimulationinterface.github.io/osi-antora-generator).
- Since the full content of the Doxygen documentation is already included in the Antora-generated documentation, there is no need for a separate Doxygen-hosted version. Therefore, the standalone Doxygen documentation should be removed.

#### Show some screenshots
OSI Documentation

### PR DESCRIPTION
**Pull request by philipwindecker**
﻿#### Reference to a related issue in the repository
#832 

#### Add a description
Remove legacy links.

#### Take this checklist as orientation for yourself, if this PR is ready for the Change Control Board:
- [ ] My suggestion follows the [style and contributors guidelines](https://opensimulationinterface.github.io/osi-antora-generator/asamosi/latest/specification/contributing/start_contributing.html).
  - Irrelevant - changes made to pipeline, not content
- [ ] I have taken care about the [message documentation](https://opensimulationinterface.github.io/osi-antora-generator/asamosi/latest/specification/contributing/commenting_messages.html) and the [fields and enums documentation](https://opensimulationinterface.github.io/osi-antora-generator/asamosi/latest/specification/contributing/commenting_fields_enums.html).
  - Irrelevant - changes made to pipeline, not content
- [x] I have done the [DCO signoff](https://opensimulationinterface.github.io/osi-documentation/open-simulation-interface/doc/howtocontribute.html#developer-certification-of-origin-dco).
- [x] My changes generate no errors when passing CI tests. 
- [ ] I have successfully implemented and tested my fix/feature locally.
  - Irrelevant - changes made to pipeline, not content
- [x] Appropriate reviewer(s) are assigned.

If you can’t check all of them, please explain why.
If all boxes are checked or commented and you have achieved at least one positive review, you can assign the label ReadyForCCBReview!

### CODE REVIEW

**Review by TimmRuppert — APPROVED** [review]
Looks good to me! Thanks! 

Just a reminder for later-me/others: To close https://github.com/OpenSimulationInterface/open-simulation-interface/issues/832 we also need a PR in this repo to cleanup the gh-pages branch (as discussed in the issue)

**Comment by TimmRuppert** [comment]
I just had a second look, I think we also should change the proto file: https://github.com/OpenSimulationInterface/open-simulation-interface/blob/b00ad2b51ad47d4338429843b6c41217dd15461c/osi_version.proto.in#L31

As expected, this shows also up in the documentation. 
image
 
 I would simply write something like: 
>  The meaning of different InterfaceVersions is defined in the versioning chapter of the official OSI documentation.

Or if somebody really wants a reference, than point to a page that actually explains this like https://opensimulationinterface.github.io/osi-antora-generator/asamosi/V3.7.0/specification/general_docs/versioning.html (this is a fixed 3.7. link..)

**Comment by jdsika** [comment]
@pmai and @engelben how would we proceed without a CCB in place? Shall I merge through the power of Grayskull

th

**Review by engelben — APPROVED** [review]
As these changes are editorial I am ok with merging this to main without a CCB. Especially as a merge to main is not equivalent to a release.

**Comment by engelben** [comment]
Let’s keep the spirit of Eternia alive! 🚀

@jdsika I am fine if you go ahead with the merge, we have enough members of the prior CCB that have approved this topic and the changes are editorial.

**Pull request merged**
