### PR TITLE
Fix old version info in release 3.3.0

### PR DESCRIPTION
**Pull request by pmai**
The v3.3.0 release of OSI has obsolete and wrong VERSION information of 3.2.0. In order to fix this problem we will have to release a v3.3.1 bug fix release with updated VERSION information, which this PR prepares.

A related question is whether we want to include the updated overview documentation in 3.3.1, if we have to do a 3.3.1 anyway.

### CODE REVIEW

**Comment by stefancyliax** [comment]
(There was already a branch vom @caspar-ai regarding this.)

@max-rosin: What do you think? Would it be possible to update the overview documentation in the near term?

**Review by stefancyliax — APPROVED** [review]
Looks good to me

**Comment by stefancyliax** [comment]
Missing: new entry in doc/releases/v03.03.rst

**Comment by kmeids** [comment]
**Output CCB 28.04.2021** :
1. @pmai  please remove "In this context, OSI defines generic interfaces to ensure modularity, integrability, and interchangeability of the individual components:" and the following image.
2. @pmai please release 3.3.1 directly after.

**Review by kmeids — APPROVED** [review]
Approved from the CCB meeting 28.04.2021

**Pull request merged**
