### PR TITLE
Extend definition of vehicles

### PR DESCRIPTION
**Pull request by carsten-kuebler**
This PR addresses issue #177 and #178

### CODE REVIEW

**Comment by CarloVanDriestenBMW** [comment]
@carsten-kuebler do you recommend to use high values for the index? Are you researching the definition?

**Comment by carsten-kuebler** [comment]
No. If you keep the Index unchanged and add new enums With a Higher values you can Merge faster. Renumber at the end.

**Comment by CarloVanDriestenBMW** [comment]
@carsten-kuebler unit missing for radius

**Comment by CarloVanDriestenBMW** [comment]
@carsten-kuebler I will do the merge

**Comment by CarloVanDriestenBMW** [comment]
@carsten-kuebler guard rails are in lane boundaries - please compare

**Comment by carsten-kuebler** [comment]
OK. I adapted also the new vehicle types with the detected probability classes.

**Pull request merged**
